[tox]
minversion = 4.0.0 # 3.10.0 
envlist = python3.13, python3.14, ruff, mypy
isolated_build = True

[gh-actions]
python =
    # 3.10: python3.10, 
    # 3.11: python3.11
    # 3.12: python3.12
    3.13: python3.13, ruff, mypy
    3.14: python3.14

[testenv]
deps = pytest
commands = pytest calculator_pkg_shrvb32846 --basetemp={envtmpdir}

[testenv:mypy]
basepython = python3.13
deps = -r {toxinidir}/requirements_dev.txt
commands = mypy calculator_pkg_shrvb32846

[testenv:ruff]
basepython = python3.13
deps = ruff
commands =
    ruff check calculator_pkg_shrvb32846
    ruff format calculator_pkg_shrvb32846
